---
apiVersion: v1
kind: Secret
metadata:
  name: "vectice-internal-ca"
type: Opaque
stringData:
  tls.crt: {{ .Values.internal.ca.cert | b64dec | quote }}
  tls.key: {{ .Values.internal.ca.key | b64dec | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: "vectice-private-https"
type: Opaque
stringData:
  tls.crt: {{ .Values.internal.ingress.cert | b64dec | quote }}
  tls.key: {{ .Values.internal.ingress.key | b64dec | quote }}