apiVersion: v2
name: vectice
description: Vectice helm chart

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)

version: 234.10

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
# It is recommended to use it with quotes.

appVersion: 234.10

# Define semver constraints on supported Kubernetes versions.
# Helm will validate the version constraints when installing the chart and fail if
# the cluster runs an unsupported Kubernetes version.
kubeVersion: ">=1.16.0-0"
dependencies:
  - name: keycloak
    version: 234.10.0
    repository: "oci://gcr.io/vectice-public/vectice/helm"
    condition: keycloak.enabled
  - name: frontend
    version: 234.10.0
    repository: "oci://gcr.io/vectice-public/vectice/helm"
    condition: frontend.enabled
  - name: backend
    version: 234.10.1
    repository: "oci://gcr.io/vectice-public/vectice/helm"
    condition: backend.enabled